# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('tracking_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('result', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('postdate', models.DateField(blank=True, default=None, null=True)),
                ('auth', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
